CREATE TABLE MST_ROLE (
 ROLE_ID INT NOT NULL PRIMARY KEY,
 ROLE_NAME VARCHAR(100),
 DELETE_FLAG BIT(1),
 UPDATED_DATE DATE,
 CREATED_DATE DATE,
 CREATED_USER INT,
 UPDATED_USER INT
);


CREATE TABLE MST_ROLE_GROUP (
 ROLE_GROUP_ID INT NOT NULL PRIMARY KEY,
 ROLE_GROUP_NAME VARCHAR(100),
 DELETE_FLAG BIT(1),
 UPDATED_DATE DATE,
 CREATED_DATE DATE,
 CREATED_USER INT,
 UPDATED_USER INT
);


CREATE TABLE ROLE_GROUP_ROLE (
 ROLE_GROUP_ROLE_ID INT NOT NULL PRIMARY KEY,
 ROLE_GROUP_ID INT,
 ROLE_ID INT,
 DELETE_FLAG BIT(1),
 UPDATED_DATE DATE,
 CREATED_DATE DATE,
 CREATED_USER INT,
 UPDATED_USER INT
);


CREATE TABLE USER_ACCOUNT (
 USER_ACCOUNT_ID INT NOT NULL PRIMARY KEY,
 LOGIN_ID VARCHAR(100),
 PASSWORD VARCHAR(100),
 ADDRESS VARCHAR(500),
 AGE INT,
 SIR_NAME VARCHAR(50),
 FAMILY_NAME VARCHAR(50),
 DELETE_FLAG BIT(1),
 UPDATED_DATE DATE,
 CREATED_DATE DATE,
 CREATED_USER INT,
 UPDATED_USER INT
);


CREATE TABLE USER_ROLE_GROUP (
 USER_ROLE_GROUP_ID INT NOT NULL PRIMARY KEY,
 USER_ID VARCHAR(100),
 ROLE_GROUP_ID INT,
 DELETE_FLAG BIT(1),
 UPDATED_DATE DATE,
 CREATED_DATE DATE,
 CREATED_USER INT,
 UPDATED_USER INT
);


