package com.example.domain;

// Generated 2015/07/07 12:06:42 by Hibernate Tools 4.3.1

/**
 * ItemType generated by hbm2java
 */
public class ItemType implements java.io.Serializable {

	private int itemTypeId;
	private Boolean deleteFlag;
	private String materialTypeName;

	public ItemType() {
	}

	public ItemType(int itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public ItemType(int itemTypeId, Boolean deleteFlag, String materialTypeName) {
		this.itemTypeId = itemTypeId;
		this.deleteFlag = deleteFlag;
		this.materialTypeName = materialTypeName;
	}

	public int getItemTypeId() {
		return this.itemTypeId;
	}

	public void setItemTypeId(int itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getMaterialTypeName() {
		return this.materialTypeName;
	}

	public void setMaterialTypeName(String materialTypeName) {
		this.materialTypeName = materialTypeName;
	}

}
