package com.example.domain;

// Generated 2015/07/08 11:31:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private String encodedPassword;
	private Set customerses = new HashSet(0);

	public Users() {
	}

	public Users(String username) {
		this.username = username;
	}

	public Users(String username, String encodedPassword, Set customerses) {
		this.username = username;
		this.encodedPassword = encodedPassword;
		this.customerses = customerses;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEncodedPassword() {
		return this.encodedPassword;
	}

	public void setEncodedPassword(String encodedPassword) {
		this.encodedPassword = encodedPassword;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
