package com.example.domain;

// Generated 2015/07/08 11:31:23 by Hibernate Tools 4.3.1

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private CustomersId id;
	private Users users;

	public Customers() {
	}

	public Customers(CustomersId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public CustomersId getId() {
		return this.id;
	}

	public void setId(CustomersId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
