package hello.world.jpa;

// Generated 2015/08/20 19:09:11 by Hibernate Tools 4.3.1



/**
 * Parents generated by hbm2java
 */
public class Parents implements java.io.Serializable {


  private long id;
  private String firstName;
  private String lastName;

  public Parents() {}

  public Parents(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getFirstName() {
    return this.firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public String getLastName() {
    return this.lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }



}
